services:
  - type: web
    name: juriaid-auth-service
    runtime: python
    rootDir: auth_service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - fromGroup: juriaid-auth-env

  - type: web
    name: juriaid-pastcase-retrieval
    runtime: python
    rootDir: past_case_retrieval
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - fromGroup: juriaid-pastcase-env

  - type: web
    name: juriaid-lawstatkg
    runtime: python
    rootDir: LawStatKG/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - fromGroup: juriaid-lawstatkg-env

  - type: web
    name: juriaid-questiongen
    runtime: python
    rootDir: questionGen
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - fromGroup: juriaid-questiongen-env

  - type: web
    name: juriaid-orchestrator
    runtime: python
    rootDir: orchestratorc
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - fromGroup: juriaid-orchestrator-env